### ISSUE TITLE
Input does not work at all with Steam VR Plugin v2.6.1

### ISSUE THREAD

**Issue by LarrxX** [ValveSoftware/unity-xr-plugin#29]
I created a new clean project, installed on **Unity 2019.4.5f1** per these instructions https://github.com/ValveSoftware/unity-xr-plugin/tree/master/com.valve.openvr 
1 - Install Steam VR Plugin (v2.6.1)
2 - Install Unity XR plugin
3 - Generate default Steam Input files

I create an XR Rig, add a Snap Turn provider (with a locomotion provider) and a Grabbable object: I can see the scene in VR, but I can't either snap turn or grab the object. All inputs (buttons and axes) are not working.

This used to work with the previous Unity Asset Store version Steam VR plugin, prior to the August 4th update.

**Comment by LarrxX** [comment]
Might be caused by issue #30 ?

**Comment by LarrxX** [comment]
It seems to be even more drastic: I hadn't noticed that "standard" OpenVR was forcefully activated (see issue #30).

When I deactivated the "Force VR" in the settings, nothing works anymore and I get errors when I click play:
![image](https://user-images.githubusercontent.com/16936069/89508405-2dcf0c00-d7ce-11ea-9b7d-d285223e4286.png)

They seem to stem from this code in OpenVRHelper.cs:
![image](https://user-images.githubusercontent.com/16936069/89508586-67077c00-d7ce-11ea-8bf7-95df95c885d2.png)

Both "GetActionsFilename" and "GetEditorAppKey" return null MethodInfos.

As is, OpenVR is totally unusable with Unity XR

**Comment by zite** [comment]
Sounds like you're trying to use Unity XR Input components? Unfortunately those won't work. Please see this post: https://github.com/ValveSoftware/unity-xr-plugin/issues/16

If you were previously not using Unity XR, and don't plan to upgrade to 2020.1+ then you can continue using the OpenVR Desktop package instead of the OpenVR XR Plugin. Just go to package manager and uninstall the OpenVR XR Plugin, reinstall OpenVR Desktop, and that should get you to a working state.
